{{- if not .Values.authService.config.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-auth.oidcSecretName" . }}
  labels:
    {{- include "oidc-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authService.config.oidc.existingSecretKey }}: {{ required "authService.config.oidc.clientSecret is required when authService.config.oidc.existingSecret is empty" .Values.authService.config.oidc.clientSecret | quote }}
{{- end }}
{{ if and .Values.redis.enabled .Values.redis.auth.acl.enabled (not .Values.redis.auth.acl.userSecret) }}
---
{{ $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-redis-acl" (include "oidc-auth.fullname" .)) -}}
{{ $passwordKey := .Values.authService.config.redis.username -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-redis-acl" (include "oidc-auth.fullname" .) }}
  labels:
    {{- include "oidc-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $passwordKey }}: {{ if and $existing (hasKey $existing.data $passwordKey) }}{{ index $existing.data $passwordKey | b64dec | quote }}{{ else }}{{ randAlphaNum 32 | quote }}{{ end }}
{{- end }}
