apiVersion: v1
kind: Service
metadata:
  name: {{ include "oidc-auth.fullname" . }}
  labels:
    {{- include "oidc-auth.labels" . | nindent 4 }}
  {{- with .Values.authService.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    {{- include "oidc-auth.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.authService.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.authService.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
